### ISSUE TITLE
Jars need investigating v2

### ISSUE THREAD

**Issue by sevenz-eth** [pickle-finance/pf-core#212]
**Cronos chain**

**Set to Withdrawal-only Jars and make them in Inactive mode :**

VVS CRO-BIFI
Reason: No more rewards

**Aurora Chain**

**Needs investigation:**

Trisolaris BBT/NEAR
Reason: Not showing APR but on the website it still in the farm page (they migrate contract?)

**Set to Withdrawal-only Jars and make them in Inactive mode :**

WANNA WANNA/AURORA
Reason: They migrate to dual reward, our page only shows 1 reward, TVL under 1k
Note: Remove pickle emission as well

PAD PAD/ROSE
Reason: They change ROSE reward to PAD reward, TVL under 1k
Note: Remove pickle emission as well

PAD FRAX/ROSE
Reason: No more rewards
Note: Remove pickle emission as well

**Moonbeam Chain**

**Set to Withdrawal-only Jars and make them in Inactive mode :**

STELLA STELLA/USDC
Reason: No more rewards

BEAM BUSD/GLMR
Reason: No more rewards

Left Phantom chain that I have not checked (gonna need thorough investigation for that chain).

@MisterMard

**Comment by rawbdor** [comment]
```

PAD PAD/ROSE
Reason: They change ROSE reward to PAD reward, TVL under 1k
Note: Remove pickle emission as well

PAD FRAX/ROSE
Reason: No more rewards
Note: Remove pickle emission as well

```

These two are showing null values on balance. May be worthwhile to debug that first.

**Comment by rawbdor** [comment]
NLP-PAD-ROSE and PAD FRAX/ROSE marked as protocol: Rose,  which is not an xyk protocol, and so pfcore had no way to determine the deposit token price. This likely never displayed this jar correctly ever. This could have been worked around if someone had overridden getDepositTokenPrice in the behavior class. But actually the correct fix is changing the protocol to NEARPAD because that's the actual protocol of the token. The token is a nearpad-style LP token.

This likely affected calculations on balance and earnable for these two jars such that they perhaps never worked.
